// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/parser/v1/parser.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarkdownParserClient is the client API for MarkdownParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarkdownParserClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type markdownParserClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkdownParserClient(cc grpc.ClientConnInterface) MarkdownParserClient {
	return &markdownParserClient{cc}
}

func (c *markdownParserClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, "/parser.v1.MarkdownParser/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkdownParserServer is the server API for MarkdownParser service.
// All implementations must embed UnimplementedMarkdownParserServer
// for forward compatibility
type MarkdownParserServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedMarkdownParserServer()
}

// UnimplementedMarkdownParserServer must be embedded to have forward compatible implementations.
type UnimplementedMarkdownParserServer struct {
}

func (UnimplementedMarkdownParserServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedMarkdownParserServer) mustEmbedUnimplementedMarkdownParserServer() {}

// UnsafeMarkdownParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkdownParserServer will
// result in compilation errors.
type UnsafeMarkdownParserServer interface {
	mustEmbedUnimplementedMarkdownParserServer()
}

func RegisterMarkdownParserServer(s grpc.ServiceRegistrar, srv MarkdownParserServer) {
	s.RegisterService(&MarkdownParser_ServiceDesc, srv)
}

func _MarkdownParser_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkdownParserServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parser.v1.MarkdownParser/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkdownParserServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkdownParser_ServiceDesc is the grpc.ServiceDesc for MarkdownParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkdownParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.v1.MarkdownParser",
	HandlerType: (*MarkdownParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _MarkdownParser_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/parser/v1/parser.proto",
}

// TypstParserClient is the client API for TypstParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypstParserClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type typstParserClient struct {
	cc grpc.ClientConnInterface
}

func NewTypstParserClient(cc grpc.ClientConnInterface) TypstParserClient {
	return &typstParserClient{cc}
}

func (c *typstParserClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, "/parser.v1.TypstParser/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypstParserServer is the server API for TypstParser service.
// All implementations must embed UnimplementedTypstParserServer
// for forward compatibility
type TypstParserServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedTypstParserServer()
}

// UnimplementedTypstParserServer must be embedded to have forward compatible implementations.
type UnimplementedTypstParserServer struct {
}

func (UnimplementedTypstParserServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedTypstParserServer) mustEmbedUnimplementedTypstParserServer() {}

// UnsafeTypstParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypstParserServer will
// result in compilation errors.
type UnsafeTypstParserServer interface {
	mustEmbedUnimplementedTypstParserServer()
}

func RegisterTypstParserServer(s grpc.ServiceRegistrar, srv TypstParserServer) {
	s.RegisterService(&TypstParser_ServiceDesc, srv)
}

func _TypstParser_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypstParserServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parser.v1.TypstParser/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypstParserServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypstParser_ServiceDesc is the grpc.ServiceDesc for TypstParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypstParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.v1.TypstParser",
	HandlerType: (*TypstParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _TypstParser_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/parser/v1/parser.proto",
}
