// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/proxy/v1/proxy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParserProxyClient is the client API for ParserProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParserProxyClient interface {
	Parse(ctx context.Context, in *ProxyParseRequest, opts ...grpc.CallOption) (*ProxyParseResponse, error)
}

type parserProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewParserProxyClient(cc grpc.ClientConnInterface) ParserProxyClient {
	return &parserProxyClient{cc}
}

func (c *parserProxyClient) Parse(ctx context.Context, in *ProxyParseRequest, opts ...grpc.CallOption) (*ProxyParseResponse, error) {
	out := new(ProxyParseResponse)
	err := c.cc.Invoke(ctx, "/proxy.v1.ParserProxy/Parse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserProxyServer is the server API for ParserProxy service.
// All implementations must embed UnimplementedParserProxyServer
// for forward compatibility
type ParserProxyServer interface {
	Parse(context.Context, *ProxyParseRequest) (*ProxyParseResponse, error)
	mustEmbedUnimplementedParserProxyServer()
}

// UnimplementedParserProxyServer must be embedded to have forward compatible implementations.
type UnimplementedParserProxyServer struct {
}

func (UnimplementedParserProxyServer) Parse(context.Context, *ProxyParseRequest) (*ProxyParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedParserProxyServer) mustEmbedUnimplementedParserProxyServer() {}

// UnsafeParserProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserProxyServer will
// result in compilation errors.
type UnsafeParserProxyServer interface {
	mustEmbedUnimplementedParserProxyServer()
}

func RegisterParserProxyServer(s grpc.ServiceRegistrar, srv ParserProxyServer) {
	s.RegisterService(&ParserProxy_ServiceDesc, srv)
}

func _ParserProxy_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserProxyServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxy.v1.ParserProxy/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserProxyServer).Parse(ctx, req.(*ProxyParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParserProxy_ServiceDesc is the grpc.ServiceDesc for ParserProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxy.v1.ParserProxy",
	HandlerType: (*ParserProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _ParserProxy_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proxy/v1/proxy.proto",
}
