// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"file-management-service/internal/biz"
	"file-management-service/internal/conf"
	"file-management-service/internal/data"
	"file-management-service/internal/server"
	"file-management-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client, err := data.NewMinioClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	writer, err := data.NewKafkaProducer(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger, client, writer)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData)
	fileUsecase := biz.NewFileUsecase(fileRepo, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, fileService, logger)
	httpServer := server.NewHTTPServer(confServer, fileService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
