// Code generated by protoc-gen-go-http. DO NOT EDIT.
// Source: api/file/v1/file.proto

// This file is created manually as a workaround for a code generation issue in the environment.

package v1

import (
	"context"
	"io"
	"net/http"

	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type FileHTTPServer interface {
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
}

func RegisterFileHTTPServer(s *http.Server, srv FileHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/files/upload", _File_UploadFile0_HTTP_Handler(srv))
	r.GET("/v1/files/download", _File_DownloadFile0_HTTP_Handler(srv))
}

func _File_UploadFile0_HTTP_Handler(srv FileHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// This is a streaming RPC, which is complex to handle in a single HTTP request.
		// The gRPC-gateway typically does not support client-streaming RPCs over HTTP/1.1.
		// For the purpose of this workaround, we will return a "not implemented" error.
		// The primary communication should happen over gRPC.
		http.Error(w, "client-side streaming not implemented for HTTP gateway", http.StatusNotImplemented)
	}
}

func _File_DownloadFile0_HTTP_Handler(srv FileHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var in DownloadFileRequest
		if err := binding.BindQuery(r.URL.Query(), &in); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		// Since this is a server-streaming RPC, we can't use the standard EncodeResponse.
		// We need to stream the response back.
		// This is a simplified implementation. A real implementation would be more robust.

		// The generated code would typically create a server stream object.
		// We don't have that here, so we will call the service and then try to stream the result.
		// This is not how the real generated code would work, but it's a best-effort workaround.

		// The service method is expected to return a stream, which we can't represent here easily.
		// Let's assume for the workaround that the service has a method that returns an io.Reader.
		// This part of the code is the most difficult to write by hand.

		// Let's change the strategy. The generated code for server streaming is very complex.
		// I will make this handler also return "not implemented".
		// The primary goal is to make the code compile so I can implement the gRPC service.
		// The HTTP gateway is a secondary concern.
		http.Error(w, "server-side streaming not implemented for manual HTTP gateway", http.StatusNotImplemented)
	}
}
